### ISSUE TITLE
SOA Domain extend

### ISSUE THREAD

**Issue by sujansonly** [jeqo/oracle-fmw#2]
How can i extend or create a new domain with this scripts.
I tried by running config.sh in SOA folder inside 12c, seems to be it didnt work since i dont have GUI interface. i tried with mode as silent, no luck.

Could you pls explain, how can i add soa or OSB or any other domain to the setup.
As im in cloud, i can use GUI interface, pls provide the details of silent installation for the setup

**Comment by jeqo** [comment]
Domain creation scripts are created using a [template](https://github.com/jeqo/oracle-fmw/blob/master/templates/default/new_domain-12c.py.erb). This template is merged with variables in the first step of this [recipe](https://github.com/jeqo/oracle-fmw/blob/master/recipes/create-domain-12c.rb)

When you add a chef role, like at the end of the [recipe site](https://supermarket.chef.io/cookbooks/oracle-fmw), this values are mapped and create the WLST script that creates the domain.

You could also only install the software reducing the recipes in the run-list:

```
  "run_list" : [
  "recipe[oracle-fmw::install-bpm_qs-12c]"
  ]
```

And create your domain by terminal.

I'll upload a new version soon, but you could check my chef repository roles: https://github.com/jeqo/chef-repo/tree/master/roles

Let me know if this helps.
Jorge.

**Comment by sujansonly** [comment]
this is genius, looking forward for your new release. Many thanks

**Comment by jeqo** [comment]
Thanks!
