### ISSUE TITLE
Setup file

### ISSUE THREAD

**Issue by sujansonly** [jeqo/oracle-fmw#4]
Hi Jeqo,

I cant find the download link for the 12c SOA Setup.
Could you please share the link for the same.

Aslo i would like to talk with you in a call, please let me know, if we can talk

Regards
Sujan

**Comment by jeqo** [comment]
Hi Sujan, 

Do you mean the SOA installers url? Go here: http://www.oracle.com/technetwork/middleware/soasuite/downloads/index.html

You can contact me at: quilcate.jorge@gmail.com

Cheers!

**Comment by sujansonly** [comment]
thank you, i will reach you through the mail

**Comment by sujansonly** [comment]
Jeqo, 

im running into this issue, when i try to run the scripts.
Im using scalr.
Below is the error.

Generated at 2016-01-15 00:13:05 +0000
NoMethodError: undefined method `delete' for #<Chef::Role:0x000000023a8c00>
/opt/chef/embedded/apps/chef/lib/chef/node.rb:340:in`consume_run_list'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:317:in `consume_attributes'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:305:in`consume_external_attrs'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:132:in `build_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:459:in`build_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in`block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in`fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in`with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in`block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in`interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in`run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:55:in`load'
/usr/bin/chef-client:55:in `<main>'

not sure, if i can bug you with this error or not.
Any help greatly appreciated.

**Comment by sujansonly** [comment]
/opt/chef/embedded/apps/chef/lib/chef/node.rb:502:in `find_or_create'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:106:in`load_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:443:in `load_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:255:in`run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in`fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in`block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in`run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in`loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in`run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in`<top (required)>'
/usr/bin/chef-client:55:in `load'
/usr/bin/chef-client:55:in`<main>'
[2016-01-15T00:31:23+00:00] DEBUG:
--- RESPONSE (404) ---
{
  "error": [
    "Object not found: chefzero://localhost:9900/nodes/ip-10-227-81-54"
  ]
}

--- END RESPONSE ---
[2016-01-15T00:31:23+00:00] DEBUG: #<ChefZero::RestRequest:0x00000001ef1f68 @env={"SCRIPT_NAME"=>"", "SERVER_NAME"=>"localhost", "REQUEST_METHOD"=>"POST", "PATH_INFO"=>"/nodes", "QUERY_STRING"=>nil, "SERVER_PORT"=>9900, "HTTP_HOST"=>"localhost:9900", "rack.url_scheme"=>"chefzero", "rack.input"=>#StringIO:0x00000001ef2080}, @rest_base_prefix=["organizations", "chef"]>
[2016-01-15T00:31:23+00:00] DEBUG: {"name":"ip-10-227-81-54","chef_environment":"dev","json_class":"Chef::Node","automatic":{},"normal":{},"chef_type":"node","default":{},"override":{},"run_list":[]}
[2016-01-15T00:31:23+00:00] DEBUG:
--- RESPONSE (201) ---
{
  "uri": "chefzero://localhost:9900/nodes/ip-10-227-81-54"
}

--- END RESPONSE ---

**Comment by sujansonly** [comment]
Hi Jeqo,

resolved this issue.we can close this incident.

Regards
Sujan
